language: generic
sudo: required
dist: trusty
env:
- SWIFT_VERSION=swift-2.2-SNAPSHOT-2015-12-01-b
install:
- SWIFT_DIR=tests
- sudo apt-get update
- sudo apt-get install clang libb64-dev uuid-dev libmysqlclient-dev mysql-server
- mkdir $SWIFT_DIR
- curl https://swift.org/builds/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C $SWIFT_DIR &> /dev/null
- sudo service mysql start
script:
- export PATH=$(pwd)/tests/$SWIFT_VERSION-ubuntu14.04/usr/bin:"${PATH}"
- swift build -c release
- .build/release/UnitTests